namespace PCCleaner.Utilities;

internal enum AppLanguage
{
    English,
    Czech
}

internal static class Localizer
{
    private static readonly Dictionary<string, string> English = new()
    {
        ["app.title"] = "PC Cleaner",
        ["app.subtitle"] = "Cache sweeper, temp folder broom, and tiny Windows cleanup console.",
        ["app.credit"] = "Created by soda144p",
        ["app.menuCredit"] = "Local author: {0}",
        ["system.detected"] = "Detected system: {0}",
        ["system.loggedIn"] = "Logged in: {0}",
        ["system.machine"] = "Machine: {0}",
        ["platform.all"] = "all OS",
        ["platform.windows"] = "Windows",
        ["platform.unknown"] = "unknown OS",
        ["animation.frame1"] = "[          ] booting cleaner core",
        ["animation.frame2"] = "[##        ] scanning dusty corners",
        ["animation.frame3"] = "[####      ] polishing console pixels",
        ["animation.frame4"] = "[######    ] warming up cache broom",
        ["animation.frame5"] = "[########  ] almost shiny",
        ["animation.frame6"] = "[##########] ready",
        ["animation.frame7"] = "[##########] creator credit: soda144p",
        ["animation.frame8"] = "[##########] checking risk labels",
        ["animation.frame9"] = "[##########] loading confirmations",
        ["animation.frame10"] = "[##########] press carefully, clean wisely",
        ["animation.hold"] = "Intro {0}/{1}. Showing creator credit before the cleaner starts.",
        ["language.choose"] = "Choose language / Vyber jazyk: 1 = English, 2 = Czech: ",
        ["language.invalid"] = "Unknown choice, using English.",
        ["admin.warning"] = "Not running as administrator. Some cleaners will skip protected locations. Use R in the menu to restart as admin.",
        ["admin.restartConfirm"] = "Restart this program as administrator now? Windows will show a UAC prompt. (Y/N): ",
        ["admin.restartStarted"] = "Restarting as administrator. This window can be closed after the elevated one opens.",
        ["admin.restartFailed"] = "Could not restart as administrator: {0}",
        ["admin.restartDeclined"] = "Admin restart cancelled.",
        ["admin.cancelled"] = "UAC prompt was cancelled.",
        ["admin.restartNoPath"] = "Could not detect the current program path.",
        ["admin.already"] = "Already running as administrator.",
        ["admin.notWindows"] = "Administrator restart is only available on Windows.",
        ["console.tooSmallTitle"] = "Console window is too small for a clean menu.",
        ["console.tooSmallSize"] = "Current size: {0}x{1}. Resize to at least {2}x{3}.",
        ["console.resizeOrQuit"] = "Resize the window to continue, or press Q to quit.",
        ["console.compactMenu"] = "Compact menu mode. Current width: {0} columns.",
        ["menu.cleaners"] = "Cleaners",
        ["menu.dashboard"] = "Dashboard",
        ["menu.number"] = "No.",
        ["menu.cleaner"] = "Cleaner",
        ["menu.details"] = "Details",
        ["menu.safe"] = "safe",
        ["menu.manual"] = "manual",
        ["menu.admin"] = "admin",
        ["menu.risk"] = "Risk",
        ["menu.unsupported"] = "unsupported here",
        ["menu.help"] = "A = quick clean   P = preview quick   E = everything   W = wave intro   R = restart as admin   Q = quit   examples: 1 3 5 or 1,3,5",
        ["prompt.choose"] = "Choose numbers, A quick, E everything, P preview quick, R admin, or Q quit: ",
        ["prompt.more"] = "Run more cleaners? (Y/N): ",
        ["prompt.start"] = "Start cleaning? (Y/N): ",
        ["prompt.confirmPreview"] = "Are you sure you want to preview these cleaners? (Y/N): ",
        ["prompt.confirmClean"] = "Are you sure you want to delete files with these cleaners? (Y/N): ",
        ["prompt.confirmCleanerPreview"] = "Are you sure you want to preview {0}? (Y/N): ",
        ["prompt.confirmCleanerClean"] = "Are you sure you want to run {0}? (Y/N): ",
        ["prompt.typeClean"] = "Type {0} to confirm real deletion: ",
        ["prompt.typeCleanWord"] = "CLEAN",
        ["status.later"] = "Later. Keep the machine tidy.",
        ["status.done"] = "Done.",
        ["status.noValid"] = "No valid cleaners selected.",
        ["status.cancelled"] = "Clean cancelled.",
        ["status.cleanWordMismatch"] = "Typed confirmation did not match. Nothing was cleaned.",
        ["status.argumentPreview"] = "Command-line preview mode is enabled. No files will be deleted.",
        ["status.ageFilter"] = "Safety filter: files newer than {0:0.##} hour(s) are skipped. Use --include-recent to override.",
        ["status.includeRecent"] = "Recent-file safety filter is disabled. Fresh files can be cleaned if selected.",
        ["status.manualWarning"] = "Manual cleaners can remove personal files if duplicates are detected.",
        ["status.skippingAdmin"] = "Skipping {0}: administrator rights are required.",
        ["status.adminRequired"] = "administrator rights required",
        ["status.unsupportedPlatform"] = "requires {0}; current system is {1}",
        ["status.windowsOnly"] = "This cleaner is Windows-only.",
        ["status.skippedByUser"] = "Skipped {0}: user did not confirm.",
        ["status.notConfirmed"] = "not confirmed",
        ["status.running"] = "Running {0}",
        ["section.ready"] = "Ready",
        ["section.summary"] = "Summary",
        ["result.total"] = "Total",
        ["result.wouldDelete"] = "would delete",
        ["result.deleted"] = "deleted",
        ["result.message"] = "{0}: {1} {2} files and {3} folders, skipped {4} recent files, freed {5}, failures: {6}.",
        ["note.recycleBin"] = "Recycle Bin contains about {0} item(s), {1} total.",
        ["note.componentPreview"] = @"Would run: schtasks.exe /Run /TN \Microsoft\Windows\Servicing\StartComponentCleanup",
        ["note.componentAccepted"] = "Windows accepted the component cleanup task. Cleanup may continue in the background.",
        ["warning.browserRunning"] = "Browser process(es) are running: {0}. Close browsers first for a cleaner and safer cache cleanup.",
        ["report.created"] = "Created",
        ["report.mode"] = "Mode",
        ["report.preview"] = "Preview",
        ["report.clean"] = "Clean",
        ["report.cleanerResults"] = "Cleaner Results",
        ["report.skipped"] = "Skipped Cleaners",
        ["report.disk"] = "Disk Space",
        ["report.diskChange"] = "Drive {0}: before {1}, after {2}, change {4}{3}.",
        ["report.ageFilter"] = "Age filter",
        ["report.ageFilterHours"] = "skip files newer than {0:0.##} hour(s)",
        ["report.ageFilterDisabled"] = "disabled; recent files included",
        ["report.saved"] = "Report saved: {0}",
        ["report.failed"] = "Could not save report: {0}",
        ["cleaner.userTemp.name"] = "User temporary files",
        ["cleaner.userTemp.description"] = "Deletes files from the current user's temp folder.",
        ["cleaner.userTemp.risk"] = "Apps may recreate temp files; open installers or apps can fail if their temp files are in use.",
        ["cleaner.windowsTemp.name"] = "Windows temporary files",
        ["cleaner.windowsTemp.description"] = "Deletes files from C:\\Windows\\Temp. Administrator rights may be needed.",
        ["cleaner.windowsTemp.risk"] = "Protected or in-use files may fail; running installs/updates should be closed first.",
        ["cleaner.crashDumps.name"] = "Crash dumps",
        ["cleaner.crashDumps.description"] = "Deletes Windows error report dumps and app crash dump files.",
        ["cleaner.crashDumps.risk"] = "You may lose crash files useful for debugging broken apps.",
        ["cleaner.windowsLogs.name"] = "Windows log files",
        ["cleaner.windowsLogs.description"] = "Deletes common .log, .tmp, and .old files from Windows temp-style log folders.",
        ["cleaner.windowsLogs.risk"] = "Troubleshooting history can be removed; admin rights are required.",
        ["cleaner.browserCache.name"] = "Browser caches",
        ["cleaner.browserCache.description"] = "Deletes common Chrome, Edge, Brave, Opera, and Firefox cache folders.",
        ["cleaner.browserCache.risk"] = "Browsers may reload websites more slowly and should be closed while cleaning.",
        ["cleaner.thumbnailCache.name"] = "Thumbnail cache",
        ["cleaner.thumbnailCache.description"] = "Deletes Windows Explorer thumbnail database files when they are not locked.",
        ["cleaner.thumbnailCache.risk"] = "Explorer may rebuild thumbnails later, causing temporary slowness.",
        ["cleaner.recentItems.name"] = "Recent items",
        ["cleaner.recentItems.description"] = "Deletes Windows recent-file shortcuts and jump-list cache files.",
        ["cleaner.recentItems.risk"] = "Recent file lists and jump-list history will disappear.",
        ["cleaner.recycleBin.name"] = "Recycle Bin",
        ["cleaner.recycleBin.description"] = "Empties the Windows Recycle Bin without prompts.",
        ["cleaner.recycleBin.risk"] = "Files in the Recycle Bin become much harder to recover.",
        ["cleaner.startup.name"] = "App startup entry",
        ["cleaner.startup.description"] = "Removes this cleaner from the current user's Windows startup entries if present.",
        ["cleaner.startup.risk"] = "Only this cleaner's startup entry is removed; it will not auto-start afterward.",
        ["cleaner.component.name"] = "Windows component cleanup task",
        ["cleaner.component.description"] = "Starts the official Windows StartComponentCleanup scheduled task for WinSxS/component cleanup.",
        ["cleaner.component.risk"] = "Windows update cleanup can take time and may remove rollback files for old components.",
        ["cleaner.duplicates.name"] = "Duplicate files in Documents",
        ["cleaner.duplicates.description"] = "Deletes duplicate files only when their size and SHA-256 hash match. Keeps the first file found.",
        ["cleaner.duplicates.risk"] = "Personal files can be deleted if they are exact duplicates; preview first."
    };

    private static readonly Dictionary<string, string> Czech = new()
    {
        ["app.title"] = "PC Cleaner",
        ["app.subtitle"] = "Maly konzolovy uklizec cache, docasnych souboru a Windows neporadku.",
        ["app.credit"] = "Vytvoril soda144p",
        ["app.menuCredit"] = "Autor na tomto PC: {0}",
        ["system.detected"] = "Detekovany system: {0}",
        ["system.loggedIn"] = "Prihlasen: {0}",
        ["system.machine"] = "Pocitac: {0}",
        ["platform.all"] = "vsechny OS",
        ["platform.windows"] = "Windows",
        ["platform.unknown"] = "neznamy OS",
        ["animation.frame1"] = "[          ] startuji cistici jadro",
        ["animation.frame2"] = "[##        ] hledam zaprasene kouty",
        ["animation.frame3"] = "[####      ] lestim konzolove pixely",
        ["animation.frame4"] = "[######    ] zahrivam cache koste",
        ["animation.frame5"] = "[########  ] skoro se to leskne",
        ["animation.frame6"] = "[##########] pripraveno",
        ["animation.frame7"] = "[##########] autor: soda144p",
        ["animation.frame8"] = "[##########] nacitam rizika",
        ["animation.frame9"] = "[##########] pripravuji potvrzeni",
        ["animation.frame10"] = "[##########] klikej opatrne, cisti moudre",
        ["animation.hold"] = "Intro {0}/{1}. Pred startem ukazuji autora.",
        ["language.choose"] = "Choose language / Vyber jazyk: 1 = English, 2 = Czech: ",
        ["language.invalid"] = "Neznama volba, pouzivam anglictinu.",
        ["admin.warning"] = "Program nebezi jako spravce. Nektere cistice preskoci chranena mista. V menu pouzij R pro restart jako spravce.",
        ["admin.restartConfirm"] = "Restartovat program jako spravce? Windows ukaze UAC potvrzeni. (A/N): ",
        ["admin.restartStarted"] = "Restartuji jako spravce. Tohle okno muzes zavrit, az se otevre nove.",
        ["admin.restartFailed"] = "Nepodarilo se restartovat jako spravce: {0}",
        ["admin.restartDeclined"] = "Restart jako spravce zrusen.",
        ["admin.cancelled"] = "Potvrzovaci dialog UAC byl zrusen.",
        ["admin.restartNoPath"] = "Nepodarilo se zjistit cestu k programu.",
        ["admin.already"] = "Program uz bezi jako spravce.",
        ["admin.notWindows"] = "Restart jako spravce je dostupny jen na Windows.",
        ["console.tooSmallTitle"] = "Okno konzole je moc male pro ciste menu.",
        ["console.tooSmallSize"] = "Aktualni velikost: {0}x{1}. Zvetsi aspon na {2}x{3}.",
        ["console.resizeOrQuit"] = "Zvetsi okno pro pokracovani, nebo stiskni Q pro konec.",
        ["console.compactMenu"] = "Kompaktni rezim menu. Aktualni sirka: {0} sloupcu.",
        ["menu.cleaners"] = "Cistice",
        ["menu.dashboard"] = "Prehled",
        ["menu.number"] = "C.",
        ["menu.cleaner"] = "Cistic",
        ["menu.details"] = "Detaily",
        ["menu.safe"] = "bezpecne",
        ["menu.manual"] = "rucni",
        ["menu.admin"] = "spravce",
        ["menu.risk"] = "Riziko",
        ["menu.unsupported"] = "tady nepodporovano",
        ["menu.help"] = "A = rychly uklid   P = nahled rychleho uklidu   E = vsechno   W = vlnove intro   R = restart jako spravce   Q = konec   priklady: 1 3 5 nebo 1,3,5",
        ["prompt.choose"] = "Vyber cisla, A rychle, E vsechno, P nahled, R spravce, nebo Q konec: ",
        ["prompt.more"] = "Spustit dalsi cistice? (A/N): ",
        ["prompt.start"] = "Zacit cistit? (A/N): ",
        ["prompt.confirmPreview"] = "Opravdu chces zobrazit nahled techto cisticu? (A/N): ",
        ["prompt.confirmClean"] = "Opravdu chces odstranit soubory temito cistici? (A/N): ",
        ["prompt.confirmCleanerPreview"] = "Opravdu chces zobrazit nahled {0}? (A/N): ",
        ["prompt.confirmCleanerClean"] = "Opravdu chces spustit {0}? (A/N): ",
        ["prompt.typeClean"] = "Pro skutecne mazani napis {0}: ",
        ["prompt.typeCleanWord"] = "CISTIT",
        ["status.later"] = "Mej se. Udrzuj stroj v cistote.",
        ["status.done"] = "Hotovo.",
        ["status.noValid"] = "Nebyl vybran zadny platny cistic.",
        ["status.cancelled"] = "Cisteni zruseno.",
        ["status.cleanWordMismatch"] = "Text potvrzeni nesedi. Nic se necistilo.",
        ["status.argumentPreview"] = "Nahledovy rezim z prikazove radky je zapnuty. Nic se nesmaze.",
        ["status.ageFilter"] = "Bezpecnostni filtr: soubory novejsi nez {0:0.##} hodin se preskoci. Prepni pomoci --include-recent.",
        ["status.includeRecent"] = "Bezpecnostni filtr cerstvych souboru je vypnuty. Nove soubory se mohou cistit.",
        ["status.manualWarning"] = "Rucni cistice mohou odstranit osobni soubory, pokud najdou duplicity.",
        ["status.skippingAdmin"] = "Preskakuji {0}: jsou potreba prava spravce.",
        ["status.adminRequired"] = "jsou potreba prava spravce",
        ["status.unsupportedPlatform"] = "vyzaduje {0}; aktualni system je {1}",
        ["status.windowsOnly"] = "Tento cistic je jen pro Windows.",
        ["status.skippedByUser"] = "Preskoceno {0}: uzivatel nepotvrdil.",
        ["status.notConfirmed"] = "nepotvrzeno",
        ["status.running"] = "Spoustim {0}",
        ["section.ready"] = "Pripraveno",
        ["section.summary"] = "Souhrn",
        ["result.total"] = "Celkem",
        ["result.wouldDelete"] = "by odstranil",
        ["result.deleted"] = "odstranil",
        ["result.message"] = "{0}: {1} {2} souboru a {3} slozek, preskoceno {4} cerstvych souboru, uvolneno {5}, selhani: {6}.",
        ["note.recycleBin"] = "Kos obsahuje priblizne {0} polozek, celkem {1}.",
        ["note.componentPreview"] = @"Spustilo by se: schtasks.exe /Run /TN \Microsoft\Windows\Servicing\StartComponentCleanup",
        ["note.componentAccepted"] = "Windows prijal ulohu cisteni komponent. Cisteni muze pokracovat na pozadi.",
        ["warning.browserRunning"] = "Bezi prohlizece: {0}. Zavri je pro cistsi a bezpecnejsi mazani cache.",
        ["report.created"] = "Vytvoreno",
        ["report.mode"] = "Rezim",
        ["report.preview"] = "Nahled",
        ["report.clean"] = "Cisteni",
        ["report.cleanerResults"] = "Vysledky cisticu",
        ["report.skipped"] = "Preskocene cistice",
        ["report.disk"] = "Misto na disku",
        ["report.diskChange"] = "Disk {0}: pred {1}, po {2}, zmena {4}{3}.",
        ["report.ageFilter"] = "Vekovy filtr",
        ["report.ageFilterHours"] = "preskocit soubory novejsi nez {0:0.##} hodin",
        ["report.ageFilterDisabled"] = "vypnuto; cerstve soubory zahrnuty",
        ["report.saved"] = "Report ulozen: {0}",
        ["report.failed"] = "Report se nepodarilo ulozit: {0}",
        ["cleaner.userTemp.name"] = "Docasne soubory uzivatele",
        ["cleaner.userTemp.description"] = "Odstrani soubory z docasne slozky aktualniho uzivatele.",
        ["cleaner.userTemp.risk"] = "Aplikace si docasne soubory znovu vytvori; otevrene instalatory nebo aplikace muzou selhat.",
        ["cleaner.windowsTemp.name"] = "Docasne soubory Windows",
        ["cleaner.windowsTemp.description"] = "Odstrani soubory z C:\\Windows\\Temp. Mohou byt potreba prava spravce.",
        ["cleaner.windowsTemp.risk"] = "Chranene nebo pouzivane soubory mohou selhat; pred cistenim zavri instalace a aktualizace.",
        ["cleaner.crashDumps.name"] = "Vypisy padu",
        ["cleaner.crashDumps.description"] = "Odstrani vypisy padu aplikaci a hlaseni chyb Windows.",
        ["cleaner.crashDumps.risk"] = "Prijdes o soubory uzitecne pro ladeni rozbitych aplikaci.",
        ["cleaner.windowsLogs.name"] = "Logy Windows",
        ["cleaner.windowsLogs.description"] = "Odstrani bezne soubory .log, .tmp, .old a .bak z logovacich/temp slozek Windows.",
        ["cleaner.windowsLogs.risk"] = "Muze zmizet historie pro reseni problemu; vyzaduje prava spravce.",
        ["cleaner.browserCache.name"] = "Cache prohlizecu",
        ["cleaner.browserCache.description"] = "Odstrani cache slozky pro Chrome, Edge, Brave, Operu a Firefox.",
        ["cleaner.browserCache.risk"] = "Weby se muzou nacitat pomaleji; prohlizece by mely byt zavrene.",
        ["cleaner.thumbnailCache.name"] = "Cache nahledu",
        ["cleaner.thumbnailCache.description"] = "Odstrani databaze nahledu Pruzkumnika Windows, pokud nejsou zamcene.",
        ["cleaner.thumbnailCache.risk"] = "Pruzkumnik bude nahledy znovu stavet, docasne muze zpomalit.",
        ["cleaner.recentItems.name"] = "Nedavne polozky",
        ["cleaner.recentItems.description"] = "Odstrani zastupce nedavnych souboru a jump-list cache.",
        ["cleaner.recentItems.risk"] = "Zmizi seznamy nedavnych souboru a historie jump-listu.",
        ["cleaner.recycleBin.name"] = "Kos",
        ["cleaner.recycleBin.description"] = "Vyprazdni Kos Windows bez dotazu.",
        ["cleaner.recycleBin.risk"] = "Soubory v Kosi bude mnohem tezsi obnovit.",
        ["cleaner.startup.name"] = "Polozka po spusteni",
        ["cleaner.startup.description"] = "Odebere tento cistic ze spousteni aktualniho uzivatele, pokud tam je.",
        ["cleaner.startup.risk"] = "Odebere se jen start tohoto cistice; po spusteni Windows uz se sam nezapne.",
        ["cleaner.component.name"] = "Cisteni komponent Windows",
        ["cleaner.component.description"] = "Spusti oficialni ulohu StartComponentCleanup pro cisteni WinSxS/komponent.",
        ["cleaner.component.risk"] = "Cisteni aktualizaci muze trvat a muze odstranit rollback soubory starych komponent.",
        ["cleaner.duplicates.name"] = "Duplicitni soubory v Dokumentech",
        ["cleaner.duplicates.description"] = "Odstrani duplicity jen pri shodne velikosti a otisku SHA-256. Prvni nalezeny soubor ponecha.",
        ["cleaner.duplicates.risk"] = "Osobni soubory mohou byt smazane, pokud jsou presne duplicity; nejdriv pouzij nahled."
    };

    public static AppLanguage CurrentLanguage { get; private set; } = AppLanguage.English;

    public static void SetLanguage(AppLanguage language)
    {
        CurrentLanguage = language;
    }

    public static string T(string key)
    {
        Dictionary<string, string> dictionary = CurrentLanguage == AppLanguage.Czech ? Czech : English;
        return dictionary.TryGetValue(key, out string? value) ? value : key;
    }

    public static string T(string key, params object[] args)
    {
        return string.Format(T(key), args);
    }
}
